name: C/C++ CI

on:
  push:
    branches: [ "android14-lineage21-mod" ]
  pull_request:
    branches: [ "android14-lineage21-mod" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: build
      run: bash build.sh cmi
