name: C/C++ CI

on:
  push:
    branches: [ "android14-lineage21-mod" ]
  pull_request:
    branches: [ "android14-lineage21-mod" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: clang install
    - run: mkdir proton-clang && cd proton-clang && wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip && unzip 20210522.zip && cd ..

    
    - name: build
    - run: bash build.sh cmi
